---

- name: ensure apt key is present
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key
    state: present

- name: ensure apt repository is present
  apt_repository:
    repo: "deb https://deb.nodesource.com/node_{{ nodejs.version }}.x bionic main"
    state: present
    update_cache: true

- name: ensure nodejs is present
  apt:
    name: nodejs
    state: present
